# Generated by Django 3.0.8 on 2020-07-22 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('title', models.CharField(max_length=150)),
                ('short_description', models.CharField(max_length=500)),
                ('content', models.FileField(upload_to='')),
                ('category', models.CharField(max_length=20)),
                ('blogid', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('is_draft', models.BooleanField(default=True)),
                ('main_img', models.ImageField(upload_to='blog-pics')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('bloggerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='/media/icons8-user-100.png', upload_to='profile-pics')),
                ('username', models.CharField(max_length=50)),
                ('bio', models.TextField()),
                ('location', models.CharField(max_length=80)),
                ('bloggerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloggerid', models.IntegerField(default=-1)),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(verbose_name='message')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('main_img', models.ImageField(default='/media/icons8-user-100.png', upload_to='')),
                ('blogid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Blogs')),
            ],
        ),
    ]
