# Generated by Django 3.0.6 on 2020-05-16 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('bloggerid', models.IntegerField()),
                ('short_description', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('img', models.ImageField(upload_to='blog_images')),
                ('category', models.CharField(max_length=20)),
            ],
        ),
    ]
