# Generated by Django 3.0.6 on 2020-05-24 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_remove_blogs_bloggerid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='img',
        ),
        migrations.AddField(
            model_name='blogs',
            name='bloggerid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
