# Generated by Django 3.0.6 on 2020-05-24 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20200524_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs_images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogid', models.IntegerField()),
                ('img', models.ImageField(upload_to='blog_images')),
            ],
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='id',
        ),
        migrations.AddField(
            model_name='blogs',
            name='blogid',
            field=models.IntegerField(default=0, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
    ]
